;; 测试 JIT 布尔字面量支持

(display "=== Testing Boolean Literals in JIT ===")
(newline)
(newline)

;; 测试 1: 布尔常量
(display "Test 1: Boolean constants")
(newline)
(display "  (use-jit true) = ")
(display (use-jit true))
(newline)
(display "  (use-jit false) = ")
(display (use-jit false))
(newline)
(newline)

;; 测试 2: not 运算
(display "Test 2: not operation")
(newline)
(display "  (use-jit (not true)) = ")
(display (use-jit (not true)))
(newline)
(display "  (use-jit (not false)) = ")
(display (use-jit (not false)))
(newline)
(newline)

;; 测试 3: and 运算
(display "Test 3: and operation")
(newline)
(display "  (use-jit (and true true)) = ")
(display (use-jit (and true true)))
(newline)
(display "  (use-jit (and true false)) = ")
(display (use-jit (and true false)))
(newline)
(display "  (use-jit (and false true)) = ")
(display (use-jit (and false true)))
(newline)
(display "  (use-jit (and false false)) = ")
(display (use-jit (and false false)))
(newline)
(newline)

;; 测试 4: or 运算
(display "Test 4: or operation")
(newline)
(display "  (use-jit (or true true)) = ")
(display (use-jit (or true true)))
(newline)
(display "  (use-jit (or true false)) = ")
(display (use-jit (or true false)))
(newline)
(display "  (use-jit (or false true)) = ")
(display (use-jit (or false true)))
(newline)
(display "  (use-jit (or false false)) = ")
(display (use-jit (or false false)))
(newline)
(newline)

;; 测试 5: 混合表达式
(display "Test 5: Mixed expressions")
(newline)
(display "  (use-jit (and (> 5 3) true)) = ")
(display (use-jit (and (> 5 3) true)))
(newline)
(display "  (use-jit (or (< 5 3) false)) = ")
(display (use-jit (or (< 5 3) false)))
(newline)
(display "  (use-jit (if true 10 20)) = ")
(display (use-jit (if true 10 20)))
(newline)
(display "  (use-jit (if false 10 20)) = ")
(display (use-jit (if false 10 20)))
(newline)
(newline)

(display "=== All boolean literal tests completed! ===")
(newline)
