;; JIT 集成全面测试

(display "=== JIT Integration Comprehensive Tests ===")
(newline)
(newline)

;; 测试 1: 算术运算
(display "Test 1: Arithmetic operations")
(newline)
(display "  (+ 1 2 3) = ")
(display (use-jit (+ 1 2 3)))
(newline)
(display "  (* 4 5) = ")
(display (use-jit (* 4 5)))
(newline)
(display "  (- 10 3) = ")
(display (use-jit (- 10 3)))
(newline)
(display "  (/ 20 4) = ")
(display (use-jit (/ 20 4)))
(newline)
(newline)

;; 测试 2: 比较运算
(display "Test 2: Comparison operations")
(newline)
(display "  (> 5 3) = ")
(display (use-jit (> 5 3)))
(newline)
(display "  (< 5 3) = ")
(display (use-jit (< 5 3)))
(newline)
(display "  (= 5 5) = ")
(display (use-jit (= 5 5)))
(newline)
(newline)

;; 测试 3: 条件表达式
(display "Test 3: Conditional expressions")
(newline)
(display "  (if (> 5 3) 10 20) = ")
(display (use-jit (if (> 5 3) 10 20)))
(newline)
(display "  (if (< 5 3) 10 20) = ")
(display (use-jit (if (< 5 3) 10 20)))
(newline)
(newline)

;; 测试 4: Lambda 表达式
(display "Test 4: Lambda expressions")
(newline)
(display "  ((lambda (x) (* x x)) 5) = ")
(display (use-jit ((lambda (x) (* x x)) 5)))
(newline)
(display "  ((lambda (a b) (+ a b)) 3 4) = ")
(display (use-jit ((lambda (a b) (+ a b)) 3 4)))
(newline)
(newline)

;; 测试 5: Let 表达式
(display "Test 5: Let expressions")
(newline)
(display "  (let ((x 10) (y 20)) (+ x y)) = ")
(display (use-jit (let ((x 10) (y 20)) (+ x y))))
(newline)
(display "  (let ((x 5)) (* x x)) = ")
(display (use-jit (let ((x 5)) (* x x))))
(newline)
(display "  (let ((x 10)) (let ((y 20)) (+ x y))) = ")
(display (use-jit (let ((x 10)) (let ((y 20)) (+ x y)))))
(newline)
(newline)

;; 测试 6: 嵌套 Lambda 和闭包
(display "Test 6: Nested lambda and closures")
(newline)
(display "  ((lambda (x) ((lambda (y) (+ x y)) 3)) 10) = ")
(display (use-jit ((lambda (x) ((lambda (y) (+ x y)) 3)) 10)))
(newline)
(newline)

;; 测试 7: 列表操作
(display "Test 7: List operations")
(newline)
(display "  (cons 1 (cons 2 nil)) = ")
(display (use-jit (cons 1 (cons 2 nil))))
(newline)
(display "  (head (cons 1 (cons 2 nil))) = ")
(display (use-jit (head (cons 1 (cons 2 nil)))))
(newline)
(display "  (tail (cons 1 (cons 2 nil))) = ")
(display (use-jit (tail (cons 1 (cons 2 nil)))))
(newline)
(newline)

;; 测试 8: 逻辑运算
(display "Test 8: Logical operations")
(newline)
(display "  (not true) = ")
(display (use-jit (not false)))
(newline)
(display "  (and true true) = ")
(display (use-jit (and true true)))
(newline)
(newline)

;; 测试 9: 复杂表达式（阶乘）
(display "Test 9: Complex expressions (factorial)")
(newline)
(display "  ((lambda (n) (if (<= n 1) 1 (* n (use-jit ((lambda (n) (if (<= n 1) 1 (* n (- n 1)))) (- n 1))))) 5) = ")
(display ((lambda (n) (if (<= n 1) 1 (* n ((lambda (n) (if (<= n 1) 1 (* n (- n 1)))) (- n 1))))) 5))
(newline)
(newline)

;; 测试 10: Set! 表达式
(display "Test 10: Set! expressions")
(newline)
(display "  (let ((x 10)) (set! x 20) x) = ")
(display (use-jit (let ((x 10)) (set! x 20) x)))
(newline)
(newline)

(display "=== All JIT integration tests completed successfully! ===")
(newline)
