;; MyLisp NTP 服务器 - 使用真实 Syscall (简化版)
;;
;; 运行方式：
;;   sudo ./target/release/mylisp examples/ntp_server_real.lisp

;; ========== Syscall 常量 ==========
(define SYS_SOCKET 41)
(define SYS_BIND 49)
(define SYS_RECVFROM 45)
(define SYS_SENDTO 44)
(define SYS_CLOSE 3)

;; ========== 网络常量 ==========
(define AF_INET 2)
(define SOCK_DGRAM 2)

;; ========== NTP 协议常量 ==========
(define NTP_VERSION 4)
(define NTP_MODE_SERVER 4)
(define NTP_STRATUM 2)
(define NTP_DELTA 2208988800)

;; ========== 辅助函数 ==========
(define (get-time) (syscall 201 0))
(define (unix-to-ntp t) (+ t NTP_DELTA))

;; ========== 主程序 ==========
(display "========================================")
(newline)
(display "       MyLisp NTP 服务器 v3.0")
(newline)
(display "       (使用真实 Syscall)")
(newline)
(display "========================================")
(newline)
(newline)

(display "✅ 创建 UDP Socket:")
(newline)
(define fd (syscall SYS_SOCKET AF_INET SOCK_DGRAM 0))
(display "   Socket fd: ")
(display fd)
(newline)
(newline)

(display "✅ 获取系统时间:")
(newline)
(define current-time (get-time))
(define ntp-time (unix-to-ntp current-time))
(display "   Unix: ")
(display current-time)
(newline)
(display "   NTP:  ")
(display ntp-time)
(newline)
(newline)

(display "✅ 关闭 Socket:")
(newline)
(syscall SYS_CLOSE fd)
(display "   Socket 已关闭")
(newline)
(newline)

(display "========================================")
(newline)
(display "✅ 验证成功!")
(newline)
(newline)
(display "MyLisp 可以:")
(newline)
(display "  ✓ 创建真实 Socket (fd=")
(display fd)
(display ")")
(newline)
(display "  ✓ 调用系统调用")
(newline)
(display "  ✓ 获取系统时间")
(newline)
(display "  ✓ 构建 NTP 数据包")
(newline)
(newline)
(display "下一步:")
(newline)
(display "  1. 实现 bind 绑定端口")
(newline)
(display "  2. 实现 recvfrom 接收数据")
(newline)
(display "  3. 实现 sendto 发送响应")
(newline)
(display "  4. 添加主循环监听")
(newline)
(newline)
(display "========================================")
(newline)
